name: BulkBlockChange
version: 1.0-SNAPSHOT
main: me.geek.tom.BulkBlockChange.BulkBlockChange
commands:
  set:
    description: set the current selection to a block
    usage: /set <block>
    aliases: []
  pos1:
    description: set pos1
    usage: /pos1
    aliases: []
  pos2:
    description: set pos2
    usage: /pos2
    aliases: []
